### ISSUE TITLE
Enumerator.ensure needs lazy monads

### ISSUE THREAD

**Issue by johnynek** [travisbrown/iteratee#105]
See:

https://github.com/travisbrown/iteratee/blob/master/core/src/main/scala/io/iteratee/Enumerator.scala#L55

since `ensure` takes a value, not a call-by-name, if the monad in question is strict, then the ensure will have already happened by the time the call is made. This leads to strange behavior with, for instance, some of the file iteratees.

I think the solution would be to take an `Eval[F[A]]` there (or a call-by-name, but in cats it seems that `Eval` is the standard way to go) so that the caller can pass `Eval.later(captureEffect(stream.close()))` which, I think is what we want.

To work around this I made a quick `Eval[M[T]]` MonadError but that was an annoying expenditure of time. (just kidding! like all fuctional programmers I secretly enjoy implementing such Monads, at least the first 10-20 times I do it).

**Comment by travisbrown** [comment]
Thanks—I've given more attention to non-strict contexts like the `Task`s and `Rerunnable`, but I think it's completely reasonable to provide any support we need for others in the core module.

**Comment by travisbrown** [comment]
@johnynek Can we consider this resolved with #106?

**Comment by johnynek** [comment]
Yessir. Thanks for all your work on this.
