### ISSUE TITLE
Reconsider scope of captureEffect with respect to hasNext on iterator 

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/iteratee#110]
See @johnynek's question [here](https://github.com/travisbrown/iteratee/pull/104#discussion_r75601421) about whether the `captureEffect` could be moved inside the first branch of the conditional in this code:
```scala
        F.flatten(
          captureEffect(
            if (iterator.hasNext) {
              val entry = iterator.next

              F.map(step.feedEl((entry, zipFile.getInputStream(entry))))(Left(_))
            } else F.pure(Right(step))
          )
        )
```

**Comment by johnynek** [comment]
Actually I think you have it right now. Encapsulation of any effect seems smart.
