### ISSUE TITLE
some `Monad[M]` can be `FlatMap[M]` in Enumerator

### ISSUE THREAD

**Issue by johnynek** [travisbrown/iteratee#111]
(maybe elsewhere).

For instance: https://github.com/travisbrown/iteratee/blob/master/core/src/main/scala/io/iteratee/Enumerator.scala#L75

some `WriterT` instances are only `FlatMap` (for instance if the type we are writing to is only a `Semigroup`). Also `Map[K, ?]` has a FlatMap but no Monad. May be a stretch, but it could be cool to imagine a bunch of parallel operations in a `FlatMap[Map[K, ?]]` that are the same up to a key. That might be a model of map/reduce?

**Comment by travisbrown** [comment]
Fixed in #118.
