### ISSUE TITLE
Example with ManagedResource[]

### ISSUE THREAD

**Issue by satyagraha** [travisbrown/iteratee#229]
Could you give an example of use of your iteratees within a Scala-ARM (J Suereth) ManagedResurce[] context? Maybe a gist?

**Comment by travisbrown** [comment]
I'm not sure exactly what this would look like. I haven't used Scala-ARM in years, but if I remember correctly it's different enough in its approach to resource management that I don't see integration as a good fit (especially when projects like cats-effect exist).

Scala-ARM also seems to be ~dead? There's no 2.13.0-Mx release, and the last substantive pull request was merged in 2016.

If someone wants to write up something like this as a blog post, I'd be happy to link to it, but I don't really see it as being something the documentation here needs very urgently.
