### ISSUE TITLE
Allow consumtion of async sources

### ISSUE THREAD

**Issue by Crafter6432** [travisbrown/iteratee#46]
Right now there doesn't seem to a way to create an Enumerator for an async source such as an scala Future.

I would propose an similar syntax to play's Enumerator.fromCallback

**Comment by travisbrown** [comment]
:+1: from me.

**Comment by travisbrown** [comment]
@Crafter6432 Can you say a little more about the use cases you'd want to support?

**Comment by Crafter6432** [comment]
I think generateM covers this now
