### ISSUE TITLE
Add helper methods for working with side-effecting iteratees

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/iteratee#53]
From Gitter, in response to [a question](https://gitter.im/travisbrown/iteratee?at=56e1887b6fde057c26858560) by @alexknvl:

> I was thinking just last week of adding something like the following methods to the Iteratee companion > object (omitting constraints and other details):
> ```scala
>def foreach[F[_], A](f: A => Unit): Iteratee[F, A, Unit]
>def foreachM[F[_], A](f: A => F[Unit]): Iteratee[F, A, Unit]
> ```
> And then on `Iteratee` instances:
> ```scala
>def discard: Iteratee[F[_], E, Unit]
>```
> I'd happily accept a PR adding these—I probably wouldn't get to them this week myself.

**Comment by alexknvl** [comment]
I'll work on it later this week if no one beats me to it.

**Comment by travisbrown** [comment]
I went ahead and put together a quick implementation in #59.

**Comment by travisbrown** [comment]
Fixed by #59.
