### ISSUE TITLE
Consider takeWhileF, etc.

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/iteratee#66]
#62 adds `takeWhile` and `dropWhile` enumeratees that take or drop values from a stream while a predicate `E => Boolean` holds. It may also be useful to have effectful versions of these enumeratees that use a predicate `E => F[Boolean]`.

**Comment by Crafter6432** [comment]
It might also be useful to be able to access the already accumulated values from takeWhile which would change the predicate to (Vector[E],E) => Boolean and (Vector[E],E) => F[Boolean] respectively.

**Comment by travisbrown** [comment]
@Crafter6432 Agreed, although we might want to allow a custom accumulator `(Acc, E) => (Acc, Boolean)` since in many cases holding on to all previous elements would be too expensive.

**Comment by Crafter6432** [comment]
@travisbrown If we do that, we could move the predicate into the accumulator `Acc => Acc` and check
`Acc.isDone` and thus avoid to instantiate the tuple.

**Comment by travisbrown** [comment]
Added by @liff in #84 and #85.
